name: Build Xiaomi nabu Kernel

on:
  workflow_dispatch:
jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:

      - name: Get branch
        id: branch
        uses: tj-actions/branch-names@v8

      - name: Set SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential make bc python2.7 python3 \
            libncurses5-dev lib32z1-dev gcc-multilib g++-multilib \
            flex bison libssl-dev device-tree-compiler
          sudo ln -sf /usr/bin/python2.7 /usr/bin/python2
          mkdir -p $GITHUB_WORKSPACE/workdir
          echo "BUILD_TIME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Get toolchain
        run: |
          git clone https://github.com/kdrag0n/proton-clang.git -b 20210522 --depth 1 $GITHUB_WORKSPACE/workdir/clang

      - name: Get source
        run: |
          git clone --recursive https://github.com/$GITHUB_REPOSITORY/ -b ${{ steps.branch.outputs.current_branch }} \
          --depth 1 $GITHUB_WORKSPACE/workdir/source

      - name: Build kernel
        run: |
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=${{ github.actor }}
          export ARCH=arm64
          export PATH="$GITHUB_WORKSPACE/workdir/clang/bin/:$PATH"
          export CROSS_COMPILE=aarch64-linux-gnu-
          cd $GITHUB_WORKSPACE/workdir/source
          make O=out sm8150-perf_defconfig CC=clang
          make -j$(nproc --all) O=out CC=clang

      - name: Verify output
        run: |
          if [ -f $GITHUB_WORKSPACE/workdir/source/out/arch/arm64/boot/Image.gz-dtb ]; then
            echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
          else
            exit 1
          fi

      - name: Package kernel
        if: env.CHECK_FILE_IS_OK == 'true'
        run: |
          git clone https://github.com/AnyKernel3/AnyKernel3.git $GITHUB_WORKSPACE/workdir/ak3
          cp $GITHUB_WORKSPACE/workdir/source/out/arch/arm64/boot/Image.gz-dtb $GITHUB_WORKSPACE/workdir/ak3
          cd $GITHUB_WORKSPACE/workdir/ak3
          zip -r9 AnyKernel3-${{ env.BUILD_TIME }}.zip *

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-${{ env.BUILD_TIME }}
          path: |
            $GITHUB_WORKSPACE/workdir/source/out/arch/arm64/boot/Image.gz-dtb
            $GITHUB_WORKSPACE/workdir/ak3/AnyKernel3-${{ env.BUILD_TIME }}.zip
